language: python

python:
  - "2.7.8"
  #- "3.4.1"

install:
  - pip install pybuilder
  - pyb install_dependencies --verbose
  - pip install python-coveralls

script:
  - pyb --verbose

after_success:
  - coveralls
