language: python

python:
  - 2.7

sudo: false

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

before_install:
  - pip install MaTiSSe.py

install:
  - pip install pybuilder
  - pyb install_dependencies --verbose
  - pip install python-coveralls

script:
  - pyb --verbose

after_success:
  - coveralls
